### ISSUE TITLE
✨ Feat: 미리보기 페이지 Nav 기능 변경

### ISSUE THREAD

**Issue by Iam-Ujin** [weniv/MAKE-RE_ver2#129]
## Description
현재 입력, 출력페이지 Nav 기능 분리가 안되어있음

## To do
미리보기 페이지일 경우
- [ ] 드래그앤드롭 기능 제거
- [ ] 체크박스 기능 제거
- [ ] 클릭 이벤트 변경(클릭시 해당 섹션으로 스크롤)
- [ ] 스크롤에 따라 변경되는 컨텐츠 활성화되도록 변경

**Comment by min-bok** [comment]
Nav가 스크롤과 함께 이동하는 기능도 추가되었으면 좋겠습니다 (floaating button과 같이)
