### ISSUE TITLE
💄 UI: NavBar 모든 필드 입력시 표시되는 체크 아이콘 제거

### ISSUE THREAD

**Issue by Iam-Ujin** [weniv/MAKE-RE_ver2#179]
## Description

체크되는 기준과 의도가 모호함에 따라 기능 제거

## To do

- [ ] 아이콘 UI및 관련 기능 제거

**Comment by imzero9** [comment]
PR #171 에서 이슈 해결되어 해당 이슈는 닫겠습니다.
