### ISSUE TITLE
🐛 Bug(or Err): 깃허브 잔디 이미지 초기화 

### ISSUE THREAD

**Issue by imzero9** [weniv/MAKE-RE_ver2#246]
## Description
- 깃허브 잔디 이미지가 새로고침 시 초기화되는 현상

## Expected
- 기존 깃허브 데이터가 있다면 새로고침 시 잔디 이미지 유지

## Todo
- 깃허브 관련 데이터 저장

**Comment by Iam-Ujin** [comment]
임시저장을 안한 상태여서 초기화되는것 같습니다 :)
임시저장을 하고도 초기화가 되는지 확인부탁드립니다!

**Comment by imzero9** [comment]
정상 동작 확인했습니다! 감사합니다 :)
