### ISSUE TITLE
✨ Feat: 아이템 타이틀 최대 글자 수 제한 

### ISSUE THREAD

**Issue by imzero9** [weniv/MAKE-RE_ver2#257]
## Description
- 작성 페이지의 아이템 컴포넌트 타이틀 글자 수 제한이 없어 버튼 UI 넘어가는 이슈 발생
- 40~45자 정도로 제한 필요

## Example
![image](https://github.com/weniv/MAKE-RE_ver2/assets/80025366/2f54b864-4b2f-4ceb-9293-03b1c547718e)

## To do
- [x] 커리어
- [x] 프로젝트
- [x] 경험
- [x] 자격증
- [x] 교육
- [x] 추가 URL

**Comment by baekg110** [comment]
## 한글 입력 시, 마지막 텍스트 출력되는 오류
- '샥'은 글자수 제한 초과
- 스페이스를 입력하거나, 클릭하는 경우 텍스트가 사라짐
![Screenshot 2024-01-04 at 11 19 53 AM](https://github.com/weniv/MAKE-RE_ver2/assets/96777064/59158528-61cb-4aa1-bd4f-830eec47174e)

**Comment by baekg110** [comment]
기존 PR 병합 후 새로운 이슈로 등록하여 작업 진행하겠습니다
