### ISSUE TITLE
💄 UI: [미리보기] 다크모드 출력 확인

### ISSUE THREAD

**Issue by min-bok** [weniv/MAKE-RE_ver2#317]
## Description
<img src="https://github.com/weniv/MAKE-RE_ver2/assets/81654172/9cfe0b07-73e3-4032-898b-55a0423f1f7b"
 width="600px" />

## To do
- 공통 컴포넌트인 날짜 컴포넌트 다크모드 적용안됨
- 커리어의 <직급> 필드 다크모드 적용안됨

**Comment by imzero9** [comment]
PR #313 에서 해결되어 해당 이슈 클로징하겠습니다 ;)
